version: '3'
services:
  ruby_database:
    container_name: ruby_database
    image: postgres
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=docker
    ports:
      - 5432:5432
    networks:
      - app-network
    volumes:
      - ./.docker/pgdata:/var/lib/postgresql
  ruby_test_database:
    container_name: ruby_test_database
    image: postgres
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=docker
    ports:
      - 5433:5432
    networks:
      - app-network
    volumes:
      - ./.docker/pgdata:/var/lib/postgresql
networks:
  app-network:
    driver: bridge